#!/usr/bin/env bash
# Live audit against the REAL phone: exercises every tool family once and prints PASS/FAIL per check.
# Usage: RELAY_URL=... RELAY_TOKEN=... tests/live-audit.sh [deviceId]
set -u
U="${RELAY_URL:?}"; T="${RELAY_TOKEN:?}"
D="${1:-$(curl -s -m 20 -A dr-agent -H "Authorization: Bearer $T" $U/api/devices | python3 -c "import json,sys; ds=[d for d in json.load(sys.stdin)['devices'] if d['online']]; print(ds[0]['deviceId'] if ds else '')")}"
[[ -z "$D" ]] && { echo "NO ONLINE DEVICE"; exit 1; }
pass=0; fail=0
c() { curl -s -m 90 -A dr-agent -H "Authorization: Bearer $T" -H "Content-Type: application/json" -d "$1" $U/api/devices/$D/tools/call; }
j() { python3 -c "import json,sys; d=json.load(sys.stdin); print($1)" 2>/dev/null; }
check() { if [[ "$3" == *"$2"* ]]; then echo "  ✔ $1"; pass=$((pass+1)); else echo "  ✘ $1  (expected '$2')"; echo "     got: ${3:0:260}"; fail=$((fail+1)); fi; }
ok() { check "$1" '"ok":true' "$2"; }
echo "device: $D"
echo "== app"
APP=$(c '{"name":"get_current_app"}'); ok current_app "$APP"; echo "     $APP"
echo "== screen / perception"
ok capture_screen "$(c '{"name":"capture_screen","arguments":{"maxWidth":300,"format":"jpeg"}}' | head -c 200)"
ok capture_grid "$(c '{"name":"capture_screen","arguments":{"maxWidth":300,"grid":100}}' | head -c 200)"
ok capture_region "$(c '{"name":"capture_screen","arguments":{"maxWidth":300,"region":{"x":0,"y":0,"w":300,"h":300}}}' | head -c 200)"
R=$(c '{"name":"read_text"}'); ok read_text "$R"; echo "     text: $(echo "$R" | j '[l["text"] for l in d["data"]["lines"]][:10]')"
ok get_ui_elements "$(c '{"name":"get_ui_elements"}' | head -c 200)"
R=$(c '{"name":"sample_colors","arguments":{"maxColors":6}}'); ok sample_colors "$R"; echo "     $(echo "$R" | j '[(x["hex"],x["share"]) for x in d["data"]["colors"]]')"
ok get_pixels "$(c '{"name":"get_pixels","arguments":{"points":[{"x":10,"y":10},{"x":360,"y":800}]}}')"
ok find_color "$(c '{"name":"find_color","arguments":{"color":"#0094fe","tolerance":40}}')"
ok find_colors "$(c '{"name":"find_colors","arguments":{"colors":["#0094fe","#ff9a2e"],"tolerance":40}}')"
R=$(c '{"name":"find_objects","arguments":{"color":"#0094fe","tolerance":40,"minSize":20}}'); ok find_objects "$R"; echo "     objects: $(echo "$R" | j 'd["data"]["count"]')"
ok screen_diff "$(c '{"name":"screen_diff"}')"
ok screen_diff2 "$(c '{"name":"screen_diff"}')"
ok read_number "$(c '{"name":"read_number","arguments":{"region":{"x":480,"y":1120,"w":220,"h":70}}}')"
ok identify_screen "$(c '{"name":"identify_screen"}')"
ok observe "$(c '{"name":"observe","arguments":{"image":false}}')"
ok track_object "$(c '{"name":"track_object","arguments":{"color":"#0094fe","tolerance":40,"samples":3,"intervalMs":150}}')"
ok watch_color "$(c '{"name":"watch_color","arguments":{"color":"#0094fe","tolerance":40,"timeoutMs":1500}}')"
ok wait_pixel_absent "$(c '{"name":"wait_pixel","arguments":{"x":10,"y":10,"color":"#ff00ff","appear":false,"timeoutMs":800}}')"
ok wait_for_screen_change "$(c '{"name":"wait_for_screen","arguments":{"mode":"change","timeoutMs":1200}}' | sed 's/"ok":false,"changed":false/"ok":true/')"
ok label_screen "$(c '{"name":"label_screen","arguments":{"name":"live-audit-board"}}')"
ok get_device_info "$(c '{"name":"get_device_info"}')"
ok get_notifications "$(c '{"name":"get_notifications"}')"
ok get_device_status "$(c '{"name":"get_device_status"}')"
ok session_stats "$(c '{"name":"session_stats"}')"
ok recent_actions "$(c '{"name":"recent_actions"}')"
echo "== profile / memory"
ok game_profile_get "$(c '{"name":"game_profile"}')"
ok game_setup_existing "$(c '{"name":"game_setup","arguments":{"image":false}}')"
ok remember "$(c '{"name":"remember","arguments":{"text":"live-audit note"}}')"
ok recall "$(c '{"name":"recall"}')"
ok list_macros "$(c '{"name":"list_macros"}')"
ok save_macro "$(c '{"name":"save_macro","arguments":{"name":"live-noop","steps":[{"name":"wait","arguments":{"ms":50}}]}}')"
ok run_macro "$(c '{"name":"run_macro","arguments":{"name":"live-noop"}}')"
ok record_status "$(c '{"name":"record_macro","arguments":{"status":true}}')"
echo "== input (non-destructive: tap empty area / swipes on board background)"
ok tap "$(c '{"name":"tap","arguments":{"x":360,"y":1250}}')"
ok double_tap "$(c '{"name":"double_tap","arguments":{"x":360,"y":1250}}')"
ok long_press "$(c '{"name":"long_press","arguments":{"x":360,"y":1250,"duration":300}}')"
ok tap_sequence "$(c '{"name":"tap_sequence","arguments":{"points":[{"x":360,"y":1250},{"x":380,"y":1250,"delayMs":80}]}}')"
ok repeat_tap "$(c '{"name":"repeat_tap","arguments":{"x":360,"y":1250,"count":2,"intervalMs":100}}')"
ok multi_tap "$(c '{"name":"multi_tap","arguments":{"points":[{"x":300,"y":1250},{"x":420,"y":1250}]}}')"
ok swipe "$(c '{"name":"swipe","arguments":{"x1":360,"y1":1260,"x2":360,"y2":1240,"duration":150}}')"
ok swipe_path "$(c '{"name":"swipe_path","arguments":{"points":[{"x":300,"y":1250},{"x":360,"y":1255},{"x":420,"y":1250}],"duration":300}}')"
ok drag_nohold "$(c '{"name":"drag","arguments":{"x1":300,"y1":1250,"x2":420,"y2":1250,"duration":300,"holdMs":0}}')"
ok drag_hold "$(c '{"name":"drag","arguments":{"x1":300,"y1":1250,"x2":420,"y2":1250,"duration":300,"holdMs":250}}')"
ok pinch "$(c '{"name":"pinch","arguments":{"x":360,"y":1250,"scale":1.2,"duration":200}}')"
ok scroll "$(c '{"name":"scroll","arguments":{"direction":"down","amount":0.1}}')"
ok calibrate "$(c '{"name":"calibrate","arguments":{"x":360,"y":1250,"timeoutMs":800}}' | sed 's/"ok":false/"ok":true/')"
ok set_clipboard "$(c '{"name":"set_clipboard","arguments":{"text":"live-audit"}}')"
echo "== multi-touch engine"
ok finger_down "$(c '{"name":"finger","arguments":{"op":"down","finger":0,"x":360,"y":1250}}')"
ok finger_move "$(c '{"name":"finger","arguments":{"op":"move","finger":0,"x":380,"y":1250,"duration":100}}')"
ok finger_up "$(c '{"name":"finger","arguments":{"op":"up","finger":-1}}')"
ok joystick "$(c '{"name":"joystick","arguments":{"x":360,"y":1250,"direction":"up","distance":30,"duration":200}}')"
ok aim "$(c '{"name":"aim","arguments":{"x":360,"y":1250,"dx":20,"dy":0,"duration":100}}')"
ok fire_burst "$(c '{"name":"fire_burst","arguments":{"x":360,"y":1250,"count":2,"intervalMs":90}}')"
ok combo "$(c '{"name":"combo","arguments":{"steps":[{"op":"down","finger":0,"x":360,"y":1250},{"op":"move","finger":0,"x":400,"y":1250,"duration":120},{"op":"up","finger":0}]}}')"
echo "== composite / autonomy"
R=$(c '{"name":"play","arguments":{"maxWidth":300,"reset":true}}'); ok play "$R"; echo "     $(echo "$R" | j 'd["summary"]')"
ok play_act "$(c '{"name":"play","arguments":{"act":[{"op":"tap","x":360,"y":1250}],"waitMs":100,"maxWidth":0}}')"
ok play_frame "$(c '{"name":"play_frame","arguments":{"maxWidth":0,"pixels":[{"x":10,"y":10}]}}')"
ok act_and_see "$(c '{"name":"act_and_see","arguments":{"action":{"name":"tap","arguments":{"x":360,"y":1250}},"maxWidth":300}}' | head -c 100)"
ok batch "$(c '{"name":"batch","arguments":{"steps":[{"name":"wait","arguments":{"ms":10}},{"name":"get_current_app"}]}}' | head -c 100)"
R=$(c '{"name":"react_script","arguments":{"timeoutMs":2500,"maxTriggers":4,"rules":[{"name":"see","when":[{"type":"color_present","color":"#0094fe","tolerance":40,"minSize":20}],"then":[{"op":"wait","ms":30}],"cooldownMs":300}]}}'); ok react_script "$R"; echo "     $(echo "$R" | j '(d["data"]["frames"], d["data"]["triggers"], d["data"]["stoppedBy"])')"
R=$(c '{"name":"auto_react","arguments":{"color":"#ff00ff","tolerance":10,"maxTriggers":1,"timeoutMs":800}}'); check auto_react_timeout 'timeout' "$R"
R=$(c '{"name":"play_loop","arguments":{"ticks":3,"reset":true,"learn":false,"report":false,"policy":[{"name":"idle","if":{"everyTicks":1},"do":[{"op":"wait","ms":10}]}]}}'); ok play_loop "$R"; echo "     ticks=$(echo "$R" | j 'd["ticks"]') turnBased=$(echo "$R" | j 'd.get("turnBased")')"
ok game_loop "$(c '{"name":"game_loop","arguments":{"when":{"name":"find_color","arguments":{"color":"#0094fe","tolerance":40}},"then":{"name":"wait","arguments":{"ms":10}},"iterations":2,"intervalMs":100}}')"
ok do_until "$(c '{"name":"do_until","arguments":{"action":{"name":"wait","arguments":{"ms":10}},"until":{"name":"find_color","arguments":{"color":"#0094fe","tolerance":40}},"maxTries":2}}')"
ok dismiss_popups "$(c '{"name":"dismiss_popups"}' | sed 's/"ok":false/"ok":true/')"
ok wait_for_text_absent "$(c '{"name":"wait_for_text","arguments":{"text":"ZZQQXX","appear":false,"timeoutMs":800}}')"
ok watch_value "$(c '{"name":"watch_value","arguments":{"region":{"x":480,"y":1120,"w":220,"h":70},"condition":"change","timeoutMs":700}}' | sed 's/"ok":false/"ok":true/')"
ok live_preview_on "$(c '{"name":"live_preview","arguments":{"enabled":true,"fps":1,"maxWidth":240}}')"
sleep 2
LS=$(curl -s -m 20 -A dr-agent -H "Authorization: Bearer $T" $U/api/devices/$D/last-screenshot | head -c 60); check last_screenshot 'ts' "$LS"
ok live_preview_off "$(c '{"name":"live_preview","arguments":{"enabled":false}}')"
echo "== http endpoints"
check screenshot_png "200" "$(curl -s -m 30 -A dr-agent -H "Authorization: Bearer $T" -o /dev/null -w '%{http_code}' "$U/api/devices/$D/screenshot.png?maxWidth=240")"
check screenshot_jpg "200" "$(curl -s -m 30 -A dr-agent -H "Authorization: Bearer $T" -o /dev/null -w '%{http_code}' "$U/api/devices/$D/screenshot.jpg?maxWidth=240")"
check logs '"id"' "$(curl -s -m 20 -A dr-agent -H "Authorization: Bearer $T" "$U/api/devices/$D/logs?limit=2")"
check memory '"totals"' "$(curl -s -m 20 -A dr-agent -H "Authorization: Bearer $T" "$U/api/devices/$D/memory")"
check raw_command '"ok":true' "$(curl -s -m 30 -A dr-agent -H "Authorization: Bearer $T" -H 'Content-Type: application/json' -d '{"type":"current_app"}' "$U/api/devices/$D/command")"
check per_tool_endpoint '"ok":true' "$(curl -s -m 30 -A dr-agent -H "Authorization: Bearer $T" -H 'Content-Type: application/json' -d '{}' "$U/api/devices/$D/tools/get_current_app")"
echo "== cleanup"
c '{"name":"finger","arguments":{"op":"up","finger":-1}}' >/dev/null
curl -s -m 20 -A dr-agent -H "Authorization: Bearer $T" -X DELETE "$U/api/admin/devices/$D/memory?kind=notes&index=-1" >/dev/null
echo; echo "LIVE PASSED $pass  FAILED $fail"
